fix: update broken links in readme file
momentohq/client-sdk-javascript pull request #1477
Opened 2024-12-07 02:49 UTC by garysassano

2025-01-02 23:28 UTC, anitarua requested changes
Hey, thanks for contributing to our repo!

Nice catch on these broken links. Do you mind fixing them in the [readme template](https://github.com/momentohq/client-sdk-javascript/blob/main/examples/nodejs/aws/eventbridge/README.template.md) instead, though?
Our readme generator in CI/CD will use that to produce the final readme

2025-01-04 02:26 UTC, garysassano commented
I reapplied the changes to the correct file.

2025-01-06 18:48 UTC, anitarua commented
Thanks, @garysassano!

One more small edit to fix this [error](https://github.com/momentohq/client-sdk-javascript/actions/runs/12592697901/job/35214264269?pr=1477) would be much appreciated:

> Error: Pull request has only one commit and it's not semantic; this may lead to a non-semantic commit in the base branch (see https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155). Amend the commit message to match the pull request title, or add another commit.

In the meantime, we're working on a way to get the remaining PR checks to pass on your branch, but will approve and merge this as soon as we are able.

2025-01-07 04:30 UTC, garysassano commented
Should be fine now.

2025-01-08 20:39 UTC, anitarua commented
Hi @garysassano! I think we have figured out how to run the PR checks on your branch. Can you sync your fork with our repo again?

I think you'll need to sync the main branch in your forked repo to get our updated workflow file, then rebase the PR branch onto the synced main branch in order to preserve your commit.

2025-01-08 20:46 UTC, garysassano commented
My branch is already in sync with main.

2025-01-09 00:53 UTC, merged