feat: add tokenId to subscriber message response
momentohq/client-sdk-javascript pull request #973
Opened 2023-10-20 17:38 UTC by pratik151192

2023-10-20 19:01 UTC, anitarua commented on packages/core/src/messages/responses/topic-item.ts
> +  public publisherID(): string | undefined {
tiny nit: `publisherID` --> `publisherId` ?

2023-10-20 19:05 UTC, anitarua approved these changes
Overall looks good to me!

2023-10-20 19:28 UTC, pratik151192 commented on packages/core/src/messages/responses/topic-item.ts
> +    if (this._publisherID) {
will add the `undefined` check explicitly

2023-10-20 19:39 UTC, pratik151192 commented on packages/core/src/messages/responses/topic-item.ts
> +  public publisherID(): string | undefined {
yes good catch will do

2023-10-20 20:05 UTC, anitarua approved these changes

2023-10-23 15:52 UTC, cprice404 requested changes

2023-10-23 16:10 UTC, cprice404 approved these changes

2023-10-23 16:16 UTC, merged